% Solve a Clustering Problem with a Self-Organizing Map
% Script generated by NCTOOL
% Created Sun Feb 22 11:59:02 IST 2015
%
% This script assumes these variables are defined:
%
%   simpleclusterInputs - input data.
clearvars;
clc;
load simplecluster_dataset;
inputs = simpleclusterInputs;

% Create a Self-Organizing Map
dimension1 = 5;
dimension2 = 5;
net = selforgmap([dimension1 dimension2]);

% Train the Network
[net,tr] = train(net,inputs);

% Test the Network
outputs = net(inputs);

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotsomtop(net)
%figure, plotsomnc(net)
%figure, plotsomnd(net)
%figure, plotsomplanes(net)
%figure, plotsomhits(net,inputs)
figure, plotsompos(net,inputs)
